### ISSUE TITLE
Barrierefreiheit

### ISSUE THREAD

**Issue by behrends** [DHBWLoerrach/CampusApp#30]
Hier diskutieren wir über die nötigen Anpassungen in der App rund um das Thema Barrierefreiheit.

**TODOs**:

- [ ] konkrete Änderungen (z.B. Kontrast der Schrift)
- [ ] Erklärung zur Barrierefreiheit
- [ ] (automatisierte) Tests auf Android-Geräten und dem iPhone
- [ ] Ergebnisse der Studienarbeit aus TIF18A berücksichtigen
- [ ] Recherchen zum Thema im Bereich mobiler Apps und React Native
- [ ] weitere Punkte?

**Comment by LouisKoenig** [comment]
Find ich gut
